"""empty message

Revision ID: 4ce205365f54
Revises: 7db102d8999a
Create Date: 2020-06-05 23:48:11.254385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ce205365f54'
down_revision = '7db102d8999a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('morphs',
    sa.Column('morph_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=60), nullable=False),
    sa.Column('base_form', sa.String(length=60), nullable=False),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('gloss', sa.String(length=60), nullable=False),
    sa.Column('pos', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['word_id'], ['words.word_id'], ),
    sa.PrimaryKeyConstraint('morph_id')
    )
    op.add_column('words', sa.Column('pos', sa.String(length=20), nullable=True))
    op.add_column('words', sa.Column('transl', sa.String(length=60), nullable=True))
    op.alter_column('words', 'gloss',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('words', 'gloss',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.drop_column('words', 'transl')
    op.drop_column('words', 'pos')
    op.drop_table('morphs')
    # ### end Alembic commands ###
