"""empty message

Revision ID: 8ace7e4e1d99
Revises: ba833afaab67
Create Date: 2024-02-27 03:36:21.170416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ace7e4e1d99'
down_revision = 'ba833afaab67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('texts', schema=None) as batch_op:
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('texts', schema=None) as batch_op:
        batch_op.alter_column('source',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=400),
               existing_nullable=True)

    # ### end Alembic commands ###
