"""empty message

Revision ID: 90778bd80082
Revises: f87c8f7fbae5
Create Date: 2020-06-04 23:06:06.187054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90778bd80082'
down_revision = 'f87c8f7fbae5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('texts',
    sa.Column('text_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('text_id')
    )
    op.create_table('paragraphs',
    sa.Column('paragraph_id', sa.Integer(), nullable=False),
    sa.Column('text_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['text_id'], ['texts.text_id'], ),
    sa.PrimaryKeyConstraint('paragraph_id')
    )
    op.create_table('phrases',
    sa.Column('phrase_id', sa.Integer(), nullable=False),
    sa.Column('paragraph_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paragraph_id'], ['paragraphs.paragraph_id'], ),
    sa.PrimaryKeyConstraint('phrase_id')
    )
    op.create_table('words',
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('phrase_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=60), nullable=False),
    sa.Column('gloss', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['phrase_id'], ['phrases.phrase_id'], ),
    sa.PrimaryKeyConstraint('word_id')
    )
    op.drop_index('ix_post_timestamp', table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_post_timestamp', 'post', ['timestamp'], unique=False)
    op.drop_table('words')
    op.drop_table('phrases')
    op.drop_table('paragraphs')
    op.drop_table('texts')
    # ### end Alembic commands ###
