"""empty message

Revision ID: a137f17c487d
Revises: 
Create Date: 2020-06-06 12:09:03.450807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a137f17c487d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('texts',
    sa.Column('text_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('text_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('paragraphs',
    sa.Column('paragraph_id', sa.Integer(), nullable=False),
    sa.Column('text_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['text_id'], ['texts.text_id'], ),
    sa.PrimaryKeyConstraint('paragraph_id')
    )
    op.create_table('phrases',
    sa.Column('phrase_id', sa.Integer(), nullable=False),
    sa.Column('paragraph_id', sa.Integer(), nullable=False),
    sa.Column('transl', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['paragraph_id'], ['paragraphs.paragraph_id'], ),
    sa.PrimaryKeyConstraint('phrase_id')
    )
    op.create_table('words',
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('phrase_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=60), nullable=False),
    sa.Column('gloss', sa.String(length=60), nullable=True),
    sa.Column('pos', sa.String(length=20), nullable=True),
    sa.Column('transl', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['phrase_id'], ['phrases.phrase_id'], ),
    sa.PrimaryKeyConstraint('word_id')
    )
    op.create_table('morphs',
    sa.Column('morph_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=60), nullable=False),
    sa.Column('base_form', sa.String(length=60), nullable=True),
    sa.Column('type', sa.String(length=60), nullable=True),
    sa.Column('gloss', sa.String(length=60), nullable=True),
    sa.Column('pos', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['words.word_id'], ),
    sa.PrimaryKeyConstraint('morph_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('morphs')
    op.drop_table('words')
    op.drop_table('phrases')
    op.drop_table('paragraphs')
    op.drop_table('users')
    op.drop_table('texts')
    # ### end Alembic commands ###
