"""empty message

Revision ID: ba833afaab67
Revises: 3b6ab35fc06b
Create Date: 2024-01-21 21:44:17.834758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba833afaab67'
down_revision = '3b6ab35fc06b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('texts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=400), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('texts', schema=None) as batch_op:
        batch_op.drop_column('source')

    # ### end Alembic commands ###
