"""empty message

Revision ID: e97278f6ac04
Revises: 03cf371ec7f4
Create Date: 2020-08-03 00:35:46.839672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e97278f6ac04'
down_revision = '03cf371ec7f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'order')
    # ### end Alembic commands ###
